ktor:
    application:
        modules:
            - ktor.ApplicationKt.module
    deployment:
        port: 8080
    database:
        driver: "org.mariadb.jdbc.Driver"
        url: "jdbc:mariadb://localhost:3307/dbGoGuide"
        username: "root"
        password: "root123"